name: aprendiendoando/Wordpress-starter-stylus
author:
  name: yan arlex vallejo
  email: aprendiendoandoo@gmail.com
  url: 'http://aprendiendoando.com'
copyright: 2015 yan arlex vallejo
description: Wordpress template starter for using Stylus
